Feature: 유저/인증 기능 개발
lgtm-code/RLC-1 pull request #6
Opened 2024-02-21 12:11 UTC by crinkj

* JWT를 사용하여 유저 회원가입/로그인/토큰 리프레쉬 API 구현하였습니다.
* Argument Resolver를 통해 인증 부분 전역으로 공통으로 사용하게 구현했습니다.
(POST /auth/refresh api에서 @Authenticated userAuth 참고)
* authService를 제외한 모든 서비스 테스트 코드 junit을 사용하여 작성하였습니다. ( 따로 테스트 환경은 분리하지 않았습니다.) 
* 밑에 swagger와 h2 databse를 통해 테스트 가능합니다. 

h2 database url - localhost:8080/webtoon-db
swagger url - localhost:8080/webtoon-api

2024-02-21 13:03 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +        return ApiResponse(userService.signUp(request))
정상 처리되었을때 응답값(데이터)이 없어서 클라이언트입장에서 요청이 정상적으로 되었는지 헷갈릴 수 있을거같네요.

2024-02-21 13:06 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +    @PostMapping("/login")
로그인도 어떻게보면 본인이 정상 사용자라는걸 인증하는거니까 AuthController에서 처리하고 UserController에서는 사용자 관리?성 API만 처리하면 어떨까 싶네요.

2024-02-21 13:09 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/domain/User.kt
> +    val tokens: MutableList<UserToken> = mutableListOf()
토큰을 1:N으로 관리하는 이유가 궁금합니다.

2024-02-21 13:19 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +class GlobalExceptionHandler {
아래에 명시해준 익셉션 말고는 해당 익셉션핸들러 로직이 작동하지 않을거 같네요.
`InvalidParameterException` 이 발생했을때는 해당 어드바이스를 타지않고 바로 예외가 클라이언트에게 던져질거 같아서 전체적인 보완이 필요할거 같아요.

2024-02-21 13:23 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/application/UserService.kt
> +        val user: User = userRepository.findByAccountId(request.accountId)
로그인 하려는 유저가 없을때, GlobalExceptionHandler 26라인의 익셉션으로 던져질거 같은데
`val user: User = userRepository.findByAccountId(request.accountId) ?: NoSuchElementException(오류 메시지)`
와 같은 방식으로 처리하여 다른 사람이 봤을때 직관적으로 어떤 에러가 나타날 수 있는지 처리하면 좋을거같아요.

2024-02-21 13:31 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +    @ExceptionHandler(value = [MalformedJwtException::class])
https://github.com/lgtm-code/RLC-1-Webtoon/pull/6/files#r1497541886
비슷한 예로 어디서 이 익셉션이 발생하는지 다른사람이 보면 왜 이걸 추가해줬는지 모를거 같네요.

2024-02-21 13:33 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/auth/presentation/AuthController.kt
> +                     @RequestParam refreshToken: String): ApiResponse<String> {
refreshToken도 클라이언트에게서 헤더값으로 받는게 맞지않을까요?

2024-02-21 13:35 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/config/AppConfig.kt
> +}
이 클래스의 용도가 궁금합니다.

2024-02-21 13:37 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +    }
로그인도 어떻게보면 본인이 정상 사용자라는걸 인증하는거니까 AuthController에서 처리하고 UserController에서는 사용자 관리?성 API만 처리하면 어떨까 싶네요.

2024-02-21 13:46 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/config/CorsConfig.kt
> +class CorsConfig : WebMvcConfigurer {
ArgumentConfig도 WebMvcConfigurer를 상속받아 구현하고 있는데 파일을 따로 분리한 이유가 있나요?

2024-02-21 13:57 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/auth/Authenticated.kt
> +annotation class Authenticated
`@Authenticated userAuth: UserAuth` 파라미터를 이용하여 이 어노테이션이 있으면 `JwtArgumentResolver.resolveArgument()`가 실행되고, 클라이언트에게서 받은 토큰을 인증하는 로직이 들어가는거 같은데, 실수로 API 필요 파라미터에 위 파라미터 혹은 어노테이션을 누락하면 토큰 검증없이 API 콜이 일어나 보안에 위험이 있을거 같아보이네요.
`HandlerInterceptor` 인터페이스를 구현한 인터셉터 로직처리가 더 편리할거 같아요.

2024-02-21 13:59 UTC, yg0313 commented
로그가 없어서 운영상 또는 테스트 과정에서 에러가 일어났을때에도, 디버깅이 힘들어보이네요 로그도 추가 되었으면 좋겠어요.

2024-02-22 01:21 UTC, dddgg9511 requested changes

2024-02-22 01:21 UTC, dddgg9511 commented on src/test/kotlin/rlc/webtoon/api/user/application/UserServiceTest.kt
> +    @Order(1)
이런식으로 order가 들어가면 각각의 테스트들이 독립적이지 않고 의존성을 가지게 되어 추후 테스트 코드를 수정하기가 힘들 수도 있을 것 같습니다.

2024-02-22 01:21 UTC, dddgg9511 commented on src/main/kotlin/rlc/webtoon/api/common/ApiError.kt
> +
common패키지내에서도 model, 과 인증 관련 설정 등 패키지를 나눠 주는게 좋을 것 같네요

2024-02-22 01:21 UTC, dddgg9511 commented on src/main/kotlin/rlc/webtoon/api/auth/presentation/JwtArgumentResolver.kt
> +        val authorization: String? = request.getHeader("Authorization")
여기서 Authorization은 따로 static 변수로 정의하거나 이미 정의되어 있는 변수를 사용해도 될 것 같네요. 리터럴은 최대한 지양하는 것이 좋을 것 같습니다

2024-02-22 01:21 UTC, dddgg9511 commented on src/main/kotlin/rlc/webtoon/api/auth/application/JwtService.kt
> +class JwtService(
이 클래스의 명칭을 service라고 붙이는 것은 모호한 것 같습니다. jwtProperties를 빈으로 주입 받는 것 외에는 util성 클래스의 역할을 하고 있는데 component로 변경하거나 config 클래스에서 빈으로 등록하는 것도 좋을 것 같습니다.

2024-02-22 01:21 UTC, dddgg9511 commented on src/test/kotlin/rlc/webtoon/api/auth/application/JwtServiceTest.kt
> +@SpringBootTest
Test의 활용되는 건 jwtService 밖에 없는데 springbootTest는 너무 무거운 것 같네요. import annotaion을 활용하거나 test 클래스내에서 jwtService 클래스만 생성해줘도 좋을 것 같아요

2024-02-24 08:07 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/user/domain/User.kt
> +    val tokens: MutableList<UserToken> = mutableListOf()
넵 실질적으로 테이블 연관관계는 1:1 이지만 jpa에서 관계는 1:N으로 잡았습니다. 이유는 n + 1 이 가장큽니다! 

참고:
https://shirohoo.github.io/spring/spring-data-jpa/2021-05-31-one-to-one/

2024-02-24 08:13 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +class GlobalExceptionHandler {
좋은 포인트인 것 같습니다! 
넵, 처음에는 명시한 예외 말고는  @ExceptionHandler(value = [Exception::class]) 을 사용해 모든 예외를 처리하려했으나 개발하면서 예외처리할 수 있는 부분은 최대한 커스텀 처리해서 하려고 컨트롤 어드바이스에서 exception으로 종합적으로 처리하진 않았습니다.  InvalidParameterException와 같이 자주 발생하는 예외 추가했습니다!

2024-02-24 08:15 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/user/application/UserService.kt
> +        val user: User = userRepository.findByAccountId(request.accountId)
넵, findbyId나 getReferenceById와 같이 엔티티 찾을 때 없는 경우는 GlobalExceptionHandler 26라인의 익셉션으로 처리되게 하였습니다. 직관성이 떨어져 보일 수 도있지만 매번 엔티티 찾는 쿼리를 찾는 경우 `?: 예외` 처리해주는 코드가 많아져 오히려 가독성이 안 좋아 질 것 같아  전역 처리하였습니다!

2024-02-24 08:23 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +    @ExceptionHandler(value = [MalformedJwtException::class])
이 부분은 jwt가 내부적으로 vefify()함수 사용시 3개 구성이 없는 경우 내부적으로 던지는 예외입니다.  그래서 예외 처리하기가 어렵더라구요. 주석으로 설명을 할까하는데 혹시 더 좋은 방법이 있을까요..?

2024-02-24 08:26 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/auth/presentation/AuthController.kt
> +                     @RequestParam refreshToken: String): ApiResponse<String> {
맞습니다!

2024-02-24 08:27 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/config/AppConfig.kt
> +}
이 클래스는 jwtProperties사용하기위해 config를 설정했습니다! 보통은 main application에 많이 설정되지만 main application대신에 따로 설정했습니다!

2024-02-24 08:28 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +    }
저도 auth에서 할지 user에서 할 지 고민하다 user에 했는데 용관님 말들어보니 auth 가 더 타탕할거 같네요.

2024-02-24 08:32 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/config/CorsConfig.kt
> +class CorsConfig : WebMvcConfigurer {
넵 같은 WebMvcConfiguerer를 상속받아도 하는 역할이 달라 설정 클래스 분리하였습니다. 만약 설정 클래스가 많아질 경우는 합칠 것 같습니다!

2024-02-24 08:44 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/auth/Authenticated.kt
> +annotation class Authenticated
넵 현재 공통 인증 객체 추출하기위해 resolveArgument를 사용했습니다. 인가 부분은 현재 필요하지 않아 구현하지 않았습니다. 결제 관련 개발할 떄 필요할 것 같아 그 때 개발 하겠습니다!

2024-02-24 08:48 UTC, crinkj commented on src/test/kotlin/rlc/webtoon/api/user/application/UserServiceTest.kt
> +    @Order(1)
아 넵넵 사실 order가 여기에서 큰 역할은 하지않습니다. 
다만 순서대로  
1-1 성공 1-2 예외 발생 
2-1 성공 2-2 예외발생
와 같은 문맥으로 보기좋게 하려고 달아놓은 어노테이션인데 처음보는 사람이 보기엔 모호하게 보이겠군요!
해당 어노테이션 제거했습니다!

2024-02-24 08:49 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/common/ApiError.kt
> +
넵 domain, client, util 로 분리하였습니다!

2024-02-24 08:50 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/auth/presentation/JwtArgumentResolver.kt
> +        val authorization: String? = request.getHeader("Authorization")
👍

2024-02-24 09:01 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/auth/application/JwtService.kt
> +class JwtService(
동욱님 말씀도 타탕하지만! 
개인적으로 jwt관련 서비스 로직을 제공하고 서비스 레이어(userService)에서도 동작하여 jwtService라 명명하였습니다.
많이 모호한가요?

2024-02-24 09:13 UTC, crinkj commented on src/test/kotlin/rlc/webtoon/api/auth/application/JwtServiceTest.kt
> +@SpringBootTest
좋은 말인것 같습니다. 너무 스프링 빈 개념에 사로잡혀 클래스 생성해서 사용하는 방법을 까먹고있엇군요! 수정했습니다!

2024-02-24 09:16 UTC, crinkj commented
> 로그가 없어서 운영상 또는 테스트 과정에서 에러가 일어났을때에도, 디버깅이 힘들어보이네요 로그도 추가 되었으면 좋겠어요.

이 부분은 코드 스타일이랑 구현 방법에 대해서 하는 코드 리뷰라 생각해서 따로 구현하지 않았습니다.

2024-02-24 09:18 UTC, crinkj commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +        return ApiResponse(userService.signUp(request))
상태값 200이 정상이라는 가정하에 응답값입니다! 그래도 따로 응답값 주는게 나을까요?

2024-02-24 13:58 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +class GlobalExceptionHandler {
최대한 커스텀하게 처리한다해도 결국 생각지못한 익셉션이 발생할 가능성이 커서 Exception은 넣어둬서 해당 핸들러를 타고 클라이언트에게 반환하도록 한후, 커스텀한 익셉션으로 후처리 하는게 더 나아보입니다.

2024-02-24 13:58 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/user/presentation/UserController.kt
> +        return ApiResponse(userService.signUp(request))
아 제기준에선 statusCode도 보지만 응답데이터가 명확한걸 선호해서 그랬습니다.

2024-02-24 14:01 UTC, yg0313 commented
> 로그가 없어서 운영상 또는 테스트 과정에서 에러가 일어났을때에도, 디버깅이 힘들어보이네요 로그도 추가 되었으면 좋겠어요.

2024-02-24 14:14 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/common/client/ApiError.kt
> +class ApiError(val error: Error, customMessage: String? = null) : RuntimeException(customMessage ?: error.message)
이 클래스에 파라미터로 throwable을 붙이면 런타임관련 익셉션을 하나의 에러핸들러로 처리 할 수 있을거같네요.

2024-02-24 14:15 UTC, yg0313 commented on src/main/kotlin/rlc/webtoon/api/common/GlobalExceptionHandler.kt
> +    @ExceptionHandler(value = [MalformedJwtException::class])
저같으면 verify() 로직을 호출하는 함수에서 try-catch로 묶어서 명시적으로 해줄것 같긴하네요 ㅎ

` try {
val parser = Jwts.parser()
                .verifyWith(secretKey)
               .build()
catch(e:JwtException) {
 throw e
}`

2024-02-26 09:28 UTC, merged